apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogs
  labels:
    svc: dogs
spec:
  selector:
    matchLabels:
      svc: dogs
  template:
    metadata:
      labels:
        svc: dogs
    spec:
      containers:
        - name: dogs
          image: quay.io/3scale/authorino:echo-api
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: dogs-api
  annotations:
    discovery.kuadrant.io/scheme: "http"
    discovery.kuadrant.io/api-name: "dogs"
    discovery.kuadrant.io/tag: "production"
    discovery.kuadrant.io/port: "80"
    discovery.kuadrant.io/matchpath: "/"
    discovery.kuadrant.io/matchpath-type: Prefix
  labels:
    discovery.kuadrant.io/enabled: "true"
spec:
  selector:
    svc: dogs
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
