# permissions for end users to edit apiproducts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiproduct-editor-role
rules:
- apiGroups:
  - networking.kuadrant.io
  resources:
  - apiproducts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.kuadrant.io
  resources:
  - apiproducts/status
  verbs:
  - get
