# permissions for end users to view apiproducts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiproduct-viewer-role
rules:
- apiGroups:
  - networking.kuadrant.io
  resources:
  - apiproducts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.kuadrant.io
  resources:
  - apiproducts/status
  verbs:
  - get
