
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apim.kuadrant.io
  resources:
  - apis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apim.kuadrant.io
  resources:
  - apis/finalizers
  verbs:
  - update
- apiGroups:
  - apim.kuadrant.io
  resources:
  - apis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apim.kuadrant.io
  resources:
  - ratelimitpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apim.kuadrant.io
  resources:
  - ratelimitpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - apim.kuadrant.io
  resources:
  - ratelimitpolicies/status
  verbs:
  - get
  - patch
  - update
