---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  namespace: istio-system
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
      - enabled: false
        name: istio-egressgateway
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
    pilot:
      enabled: true
  values:
    pilot:
      autoscaleEnabled: false
    gateways:
      istio-ingressgateway:
        type: ClusterIP
        autoscaleEnabled: false
    global:
      istioNamespace: istio-system
