---
apiVersion: apim.kuadrant.io/v1alpha1
kind: RateLimitPolicy
metadata:
  name: carstore
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: carstore
  rules:
    - operations:
        - paths: ["/car"]
          methods: ["GET"]
      rateLimits:
        - stage: PREAUTH
          actions:
            - generic_key:
                descriptor_key: get-car
                descriptor_value: "yes"
  domain: carstore-app
  limits:
    - conditions: ["get-car== yes"]
      max_value: 2
      namespace: carstore-app
      seconds: 30
      variables: []
