---
apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  creationTimestamp: null
  name: toystore
spec:
  hosts:
    - api.toystore.com
  identity:
    - apiKey:
        labelSelectors:
          app: toystore
          authorino.kuadrant.io/managed-by: authorino
      credentials:
        in: authorization_header
        keySelector: APIKEY
      name: apikey
  response:
    - json:
        properties:
          - name: user-id
            value: null
            valueFrom:
              authJSON: auth.identity.metadata.annotations.secret\.kuadrant\.io/user-id
      name: rate-limit-apikey
      wrapper: envoyDynamicMetadata
      wrapperKey: ext_auth_data
