---
apiVersion: apim.kuadrant.io/v1alpha1
kind: RateLimitPolicy
metadata:
  name: toystore
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  rules:
    - operations:
        - paths: ["/toy"]
          methods: ["GET"]
      rateLimits:
        - stage: PREAUTH
          actions:
            - generic_key:
                descriptor_key: get-toy
                descriptor_value: "yes"
    - operations:
        - paths: ["/admin/toy"]
          methods: ["POST", "DELETE"]
      rateLimits:
        - stage: POSTAUTH
          actions:
            - generic_key:
                descriptor_key: admin
                descriptor_value: "yes"
  rateLimits:
    - stage: BOTH
      actions:
        - generic_key:
            descriptor_key: vhaction
            descriptor_value: "yes"
  domain: toystore-app
  limits:
    - conditions: ["get-toy == yes"]
      max_value: 2
      namespace: toystore-app
      seconds: 30
      variables: []
    - conditions:
      - "admin == yes"
      - "user-id == bob"
      max_value: 2
      namespace: toystore-app
      seconds: 30
      variables: []
    - conditions:
      - "addmin == yes"
      - "user-id == alice"
      max_value: 4
      namespace: toystore-app
      seconds: 30
      variables: []
    - conditions: ["vhaction == yes"]
      max_value: 6
      namespace: toystore-app
      seconds: 30
      variables: []
