---
apiVersion: apim.kuadrant.io/v1alpha1
kind: RateLimitPolicy
metadata:
  name: toystore
spec:
  routes:
    - name: get-toy
      rateLimits:
        - stage: BOTH
          actions:
            - generic_key:
                descriptor_key: get-toy
                descriptor_value: "yes"
            - generic_key:
                descriptor_key: other-get-toy
                descriptor_value: "yes"
    - name: add-toy
      rateLimits:
        - stage: POSTAUTH
          actions:
            - generic_key:
                descriptor_key: add-toy
                descriptor_value: "yes"
    - name: delete-toy
      rateLimits:
        - stage: PREAUTH
          actions:
            - generic_key:
                descriptor_key: delete-toy
                descriptor_value: "yes"
  rateLimits:
    - stage: PREAUTH
      actions:
        - generic_key:
            descriptor_key: vhaction
            descriptor_value: "yes"
        - request_headers:
            descriptor_key: "path"
            header_name: ":path"
        - remote_address: {}
    - stage: POSTAUTH
      actions:
        - metadata:
            descriptor_key: "user_id"
            metadata_key:
              key: "envoy.filters.http.ext_authz"
              path:
                - key: "ext_auth_data"
                - key: "user_id"
  limits:
    - conditions: ["get-toy == yes"]
      max_value: 2
      namespace: preauth
      seconds: 30
      variables: []
    - conditions: ["add-toy == yes"]
      max_value: 2
      namespace: postauth
      seconds: 30
      variables: []
    - conditions: ["vhaction == yes"]
      max_value: 6
      namespace: preauth
      seconds: 30
      variables: []
