---
apiVersion: apim.kuadrant.io/v1alpha1
kind: RateLimitPolicy
metadata:
  name: toystore
spec:
  rules:
    - name: get-toy
      operation:
        paths: ["/toy"]
        methods: ["GET"]
        hosts: ["*.toystore.com"]
      rateLimits:
        - stage: BOTH
          actions:
            - generic_key:
                descriptor_key: get-toy
                descriptor_value: "yes"
            - generic_key:
                descriptor_key: other-get-toy
                descriptor_value: "yes"
    - name: add-toy
      rateLimits:
        - stage: POSTAUTH
          actions:
            - generic_key:
                descriptor_key: add-toy
                descriptor_value: "yes"
    - name: delete-toy
      rateLimits:
        - stage: PREAUTH
          actions:
            - generic_key:
                descriptor_key: delete-toy
                descriptor_value: "yes"
  rateLimits:
    - stage: PREAUTH
      actions:
        - generic_key:
            descriptor_key: vhaction
            descriptor_value: "yes"
  domain: toystore-app
  limits:
    - conditions: ["get-toy == yes"]
      max_value: 2
      namespace: toystore-app
      seconds: 30
      variables: []
    - conditions: ["add-toy == yes"]
      max_value: 2
      namespace: toystore-app
      seconds: 30
      variables: []
    - conditions: ["vhaction == yes"]
      max_value: 6
      namespace: toystore-app
      seconds: 30
      variables: []
