---
apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
spec:
  clusterWide: true
  image: quay.io/3scale/authorino:v0.7.0
  listener:
    tls:
      enabled: false
  logLevel: debug
  oidcServer:
    tls:
      enabled: false
