apiVersion: v1
kind: Secret
metadata:
  name: user-secret-apikey
  annotations:
    secret.kuadrant.io/user-id: bob
  labels:
    secret.kuadrant.io/managed-by: authorino
    api: store
stringData:
  api_key: JUSTFORDEMO
type: Opaque
