//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteRef) DeepCopyInto(out *HTTPRouteRef) {
	*out = *in
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteRef.
func (in *HTTPRouteRef) DeepCopy() *HTTPRouteRef {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WASMFilter) DeepCopyInto(out *WASMFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WASMFilter.
func (in *WASMFilter) DeepCopy() *WASMFilter {
	if in == nil {
		return nil
	}
	out := new(WASMFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WASMFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WASMFilterList) DeepCopyInto(out *WASMFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WASMFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WASMFilterList.
func (in *WASMFilterList) DeepCopy() *WASMFilterList {
	if in == nil {
		return nil
	}
	out := new(WASMFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WASMFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WASMFilterSpec) DeepCopyInto(out *WASMFilterSpec) {
	*out = *in
	in.HTTPRouteRef.DeepCopyInto(&out.HTTPRouteRef)
	in.PluginConfig.DeepCopyInto(&out.PluginConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WASMFilterSpec.
func (in *WASMFilterSpec) DeepCopy() *WASMFilterSpec {
	if in == nil {
		return nil
	}
	out := new(WASMFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WASMFilterStatus) DeepCopyInto(out *WASMFilterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WASMFilterStatus.
func (in *WASMFilterStatus) DeepCopy() *WASMFilterStatus {
	if in == nil {
		return nil
	}
	out := new(WASMFilterStatus)
	in.DeepCopyInto(out)
	return out
}
