# Copyright 2020 The Knative Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is automagically synced here from github.com/knative-sandbox/.github
# repo by knobots: https://github.com/knative-sandbox/knobots and will be overwritten.
---
name: Testing
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  unittests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: run tests
        run: |
          make test-unit
  integrationtests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.1
          config: utils/local-deployment/kind-cluster.yaml
          cluster_name: kuadrant-local
          wait: 120s
      - name: Check cluster info
        run: |
          kubectl cluster-info dump
      - name: Deploy Kuadrant deps
        run: |
          make local-env-setup
      - name: run tests
        run: |
          make test-integration
  verify-manifests:
    name: Verify manifests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run make verify-manifests
        run: |
          make verify-manifests
  verify-fmt:
    name: Verify fmt
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run make verify-fmt
        run: |
          make verify-fmt
